version: '3.8'
services:
  hasura:
    image: hasura/graphql-engine:v2.10.1
    container_name: skrrrt_hasura
    expose:
      - 8080
    restart: unless-stopped
    env_file:
      - ./.env.production

  iframely:
    image: coloradocolby/iframely:latest
    container_name: skrrrt_iframely
    expose:
      - 8061
    restart: unless-stopped
    volumes:
      - $PWD/iframely.config.js:/iframely/config.local.js
    env_file:
      - ./.env.production

  caddy:
    image: caddy:2-alpine
    container_name: skrrrt_caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
